//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class grades_database
    {
        public int grade_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public string grade { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual user user { get; set; }
    }
}
