//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_of_users
    {
        public type_of_users()
        {
            this.users = new HashSet<user>();
        }
    
        public int type_of_user_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
