//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.courses = new HashSet<cours>();
        }
    
        public long users_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public int type_of_user { get; set; }
        public string phone_number { get; set; }
        public string address_firstline { get; set; }
        public string address_secondline { get; set; }
        public string address_city { get; set; }
        public string postcode { get; set; }
        public string profile_picture { get; set; }
        public string description { get; set; }
    
        public virtual type_of_users type_of_users { get; set; }
        public virtual ICollection<cours> courses { get; set; }
    }
}
